//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTC_MO_HINH_CONG_TY
    {
        public CCTC_MO_HINH_CONG_TY()
        {
            this.CCTC_CONG_TY = new HashSet<CCTC_CONG_TY>();
        }
    
        public string MA_MO_HINH { get; set; }
        public string TEN_MO_HINH { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<CCTC_CONG_TY> CCTC_CONG_TY { get; set; }
    }
}
