//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTC_PHONG_BAN
    {
        public CCTC_PHONG_BAN()
        {
            this.CCTC_NHAN_VIEN = new HashSet<CCTC_NHAN_VIEN>();
        }
    
        public string MA_PHONG_BAN { get; set; }
        public string TEN_PHONG_BAN { get; set; }
        public string SDT { get; set; }
        public string MA_CONG_TY { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual ICollection<CCTC_NHAN_VIEN> CCTC_NHAN_VIEN { get; set; }
    }
}
