//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTC_NHAN_VIEN
    {
        public string USERNAME { get; set; }
        public string GIOI_TINH { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string QUE_QUAN { get; set; }
        public string TRINH_DO_HOC_VAN { get; set; }
        public string MA_PHONG_BAN { get; set; }
    
        public virtual CCTC_PHONG_BAN CCTC_PHONG_BAN { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
    }
}
