//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_CHI_TIET_NGHIEP_VU
    {
        public CN_CHI_TIET_NGHIEP_VU()
        {
            this.CN_NGHIEP_VU_NHAN_VIEN = new HashSet<CN_NGHIEP_VU_NHAN_VIEN>();
            this.CN_NHOM_NGHIEP_VU = new HashSet<CN_NHOM_NGHIEP_VU>();
        }
    
        public int ID { get; set; }
        public string TEN_CHI_TIET { get; set; }
        public string ID_NGHIEP_VU { get; set; }
        public string MO_TA { get; set; }
    
        public virtual CN_NGHIEP_VU CN_NGHIEP_VU { get; set; }
        public virtual ICollection<CN_NGHIEP_VU_NHAN_VIEN> CN_NGHIEP_VU_NHAN_VIEN { get; set; }
        public virtual ICollection<CN_NHOM_NGHIEP_VU> CN_NHOM_NGHIEP_VU { get; set; }
    }
}
