//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HANG_HOA
    {
        public DM_HANG_HOA()
        {
            this.DM_HANG_TON_KHO = new HashSet<DM_HANG_TON_KHO>();
            this.DM_TONKHO_HANG = new HashSet<DM_TONKHO_HANG>();
        }
    
        public string MA_HANG_HT { get; set; }
        public string MA_HANG_NHAP { get; set; }
        public string TEN_HANG { get; set; }
        public string MA_NHOM_HANG { get; set; }
        public string SERI { get; set; }
        public string DON_VI_TINH { get; set; }
        public Nullable<bool> MODEL_DAC_BIET { get; set; }
        public string HINH_ANH { get; set; }
        public string DAC_TINH { get; set; }
        public string GHI_CHU { get; set; }
        public string TK_HACH_TOAN_KHO { get; set; }
        public string TK_DOANH_THU { get; set; }
        public string TK_CHI_PHI { get; set; }
        public string XUAT_XU { get; set; }
    
        public virtual DM_HANG_SP DM_HANG_SP { get; set; }
        public virtual ICollection<DM_HANG_TON_KHO> DM_HANG_TON_KHO { get; set; }
        public virtual ICollection<DM_TONKHO_HANG> DM_TONKHO_HANG { get; set; }
        public virtual DM_TAI_KHOAN_HACH_TOAN DM_TAI_KHOAN_HACH_TOAN { get; set; }
        public virtual DM_TAI_KHOAN_HACH_TOAN DM_TAI_KHOAN_HACH_TOAN1 { get; set; }
        public virtual DM_TAI_KHOAN_HACH_TOAN DM_TAI_KHOAN_HACH_TOAN2 { get; set; }
    }
}
