//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHO
    {
        public DM_KHO()
        {
            this.DM_HANG_TON_KHO = new HashSet<DM_HANG_TON_KHO>();
            this.DM_KHO1 = new HashSet<DM_KHO>();
        }
    
        public string MA_KHO { get; set; }
        public string TEN_KHO { get; set; }
        public string DIA_CHI_KHO { get; set; }
        public string MA_KHO_CHA { get; set; }
        public string TRUC_THUOC { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual ICollection<DM_HANG_TON_KHO> DM_HANG_TON_KHO { get; set; }
        public virtual ICollection<DM_KHO> DM_KHO1 { get; set; }
        public virtual DM_KHO DM_KHO2 { get; set; }
    }
}
