//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NGUOI_DUNG
    {
        public HT_NGUOI_DUNG()
        {
            this.CN_NGHIEP_VU_NHAN_VIEN = new HashSet<CN_NGHIEP_VU_NHAN_VIEN>();
        }
    
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string HO_VA_TEN { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string AVATAR { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public bool ALLOWED { get; set; }
        public string MA_CONG_TY { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual ICollection<CN_NGHIEP_VU_NHAN_VIEN> CN_NGHIEP_VU_NHAN_VIEN { get; set; }
    }
}
